"""change obselescence data

Revision ID: 1260f63e32b1
Revises: 454a0ab5dd65
Create Date: 2025-08-06 19:52:09.587028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1260f63e32b1'
down_revision: Union[str, Sequence[str], None] = '454a0ab5dd65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('obsolescence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metrics', 'obsolescence')
    # ### end Alembic commands ###
