"""add item id

Revision ID: 454a0ab5dd65
Revises: 84787d5dbf48
Create Date: 2025-08-06 12:41:02.078789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '454a0ab5dd65'
down_revision: Union[str, Sequence[str], None] = '84787d5dbf48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layout_items', 'metric_configuration_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layout_items', sa.Column('metric_configuration_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
