"""modify metric data table

Revision ID: e12ca7e74732
Revises: 6ecc9173dbb5
Create Date: 2025-08-06 01:21:25.765606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e12ca7e74732'
down_revision: Union[str, Sequence[str], None] = '6ecc9173dbb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('metric_id', sa.String(), nullable=False))
    op.alter_column('metrics', 'id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('metrics', 'id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('metrics', 'metric_id')
    # ### end Alembic commands ###
