"""add core entities

Revision ID: eaa23960c4f9
Revises: 6ecc9173dbb5
Create Date: 2025-08-06 10:31:49.859722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa23960c4f9'
down_revision: Union[str, Sequence[str], None] = '6ecc9173dbb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_configurations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('query_id', sa.String(), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layout_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('breakpoint', sa.String(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('w', sa.Integer(), nullable=True),
    sa.Column('h', sa.Integer(), nullable=True),
    sa.Column('static', sa.Boolean(), nullable=True),
    sa.Column('metric_configuration_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['metric_configuration_id'], ['metric_configurations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('layout_items')
    op.drop_table('metric_configurations')
    op.drop_table('queries')
    # ### end Alembic commands ###
