name: CI/CD Pipeline

on:
  push:
    branches: [ trunk ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout head
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install dependencies with Poetry
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
      - name: Run tests with pytest
        run: |
          pytest