name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout head
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install dependencies with Poetry
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
      - name: Run tests with pytest
        run: |
          set -a
          source .env.local
          set +a
          pytest
      - name: Deploy SAM app
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          AWS_REGION: eu-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          INSTANCE_ID=$(aws cloudformation describe-stacks \
            --stack-name metrics-api-prod \
            --region $AWS_REGION \
            --query "Stacks[0].Outputs[?OutputKey=='EC2InstanceID'].OutputValue" \
            --output text)
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
          sam deploy \
            --no-fail-on-empty-changeset \
            --template-file deploy-template.yml \
            --stack-name metrics-api-prod \
            --s3-bucket metrics-api-prod-s3 \
            --s3-prefix metrics \
            --region $AWS_REGION \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides DBPassword=$DB_PASSWORD KeyName=intropy-ec2-keypair $REBUILD_PARAM \
            --no-confirm-changeset
      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem
      - name: Setup known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      - name: Copy code to EC2
        run: |
          scp -i ec2_key.pem -r ./* ec2-user@${{ secrets.EC2_HOST }}:~/app/
      - name: Check env vars before SSH
        run: |
          echo "INSTANCE_ID=${{ env.INSTANCE_ID }}"
          echo "COMMIT_MSG=${{ github.event.head_commit.message }}"
      - name: Deploy Docker app on EC2
        uses: appleboy/ssh-action@v0.1.7
        env:
          INSTANCE_ID: ${{ env.INSTANCE_ID }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            export INSTANCE_ID="${{ env.INSTANCE_ID }}"
            export COMMIT_MSG="${{ github.event.head_commit.message }}"
      
            echo "COMMIT_MSG: $COMMIT_MSG"
            echo "INSTANCE_ID: $INSTANCE_ID"
            
            env | grep INSTANCE
            env | grep COMMIT
            
            if [[ "$COMMIT_MSG" == *"--ec2init" ]]; then
              echo "Commit ends with --ec2init, running user-data script..."
              sudo bash -x /var/lib/cloud/instances/$INSTANCE_ID/user-data.txt
            else
              echo "Commit does not end with --ec2init, skipping user-data script."
            fi
            
            set -e
            cd ~/app || mkdir ~/app && cd ~/app
            docker build -t myfastapiapp .
            if [ "$(docker ps -q -f name=myfastapiapp)" ]; then
              docker stop myfastapiapp
              docker rm myfastapiapp
            fi
            docker run -d --restart unless-stopped --name myfastapiapp --env-file /home/ec2-user/fastapi.env -p 8000:8000 myfastapiapp